### ISSUE TITLE
Question about data preprocessing for semanticKITTI

### ISSUE THREAD

**Issue by liamlin5566** [zgojcic/Rigid3DSceneFlow#16]
Hi, thanks for sharing. 
I wonder why you remove the points invisible within the front camera for semanticKITTI. Based on your paper, it doesn't seem necessary.Is it any difference when I use full point cloud to test or train?

**Comment by zgojcic** [comment]
Hi.

thank you for your question. While I think that using whole PCs would not make a large difference, we use the semanticKITTI as a large dataset on which we can train our method and then evaluate it on lidarKITTI. In lidarKITTI the GT scene flow which is used for evaluation is obtained by projecting the pointclouds to the camera image plane. Therefore, lidarKITTI can only contain points that project to the front camera. As we are using semanticKITTI to train our model, we then process it in the same way to not have a large domain gap.

In the paper, we state the following: 
`
We train a joint model for both scenarios in a weakly supervised manner using the point clouds from semanticKITTI. Unlike semanticKITTI, lidarKITTI only includes the points and annotations of the objects that are visible within the front camera images. We therefore process semanticKITTI in the same manner. Since there are no LiDAR datasets available with scene flow annotations, we use the models trained on FT3D for all the baselines.`

I hope that this answers your question.

Best
Zan

**Comment by liamlin5566** [comment]
Thanks for your response.  I will try it.
